openapi: 3.0.3
info:
  title: Mail store
  version: 0.0.4
paths:
  '/api/mail/{id}':
    get:
      operationId: findById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mail'
        '400':
          description: default response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: default response
          content:
            application/json:
              schema:
                type: string
    put:
      operationId: updateMail
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mail'
      responses:
        '200':
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mail'
        '400':
          description: default response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: default response
          content:
            application/json:
              schema:
                type: string
    delete:
      operationId: deleteMail
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: default response
          content:
            application/json:
              schema:
                type: string
        '400':
          description: default response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: default response
          content:
            application/json:
              schema:
                type: string
    patch:
      operationId: patchMail
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Mail'
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Mail'
        '400':
          description: default response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: default response
          content:
            application/json:
              schema:
                type: string
    post:
      operationId: doActionMail
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MailAction'
      responses:
        '201':
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MailAction'
        '400':
          description: default response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: default response
          content:
            application/json:
              schema:
                type: string
            
  /api/mail/:
    get:
      operationId: findMails
      responses:
        '200':
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mail'
        '400':
          description: default response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: default response
          content:
            application/json:
              schema:
                type: string
    post:
      operationId: postMail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mail'
      responses:
        '201':
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mail'
        '400':
          description: default response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: default response
          content:
            application/json:
              schema:
                type: string
    head:
      operationId: headMail
      responses:
        '200':
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mail'
        '400':
          description: default response
          content:
            application/json:
              schema:
                type: string
        '404':
          description: default response
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Mail:
      required:
        - issuer
        - subject
        - type
      type: object
      properties:
        id:
          type: string
        subject:
          type: string
        issuer:
          $ref: '#/components/schemas/Actor'
        type:
          type: string
          enum: [email, cmail, cmail, pmail]
        actors:
          type: array
          items:
            $ref: '#/components/schemas/Actor'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
    Actor:
      required:
        - name
        - type
        - state
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum: [issuer, sender, recipient, validator, signer]
        state:
          type: string
    MailAction:
      required:
        - type
        - data
      properties:
        type:
          type: string
          enum: [send, validate, sign, refuse, remove, cancel, transfert, forward]
        data:
          type: object
    Document:
      required:
        - name
        - type
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum: [main, attachment]
        data:
          type: object
          
